FROM tomcat:latest

LABEL ORGANIZATION="www.unixcloudtrainings.com"

COPY ./webapp.war /usr/local/tomcat/webapps

#Create Dockerfile under /opt/k8s-lab/"file-name"
#Which means /k8s-lab/ directory should be created before creating Dockerfile "file"
#sudo chown -R ubuntu:ubuntu k8s-lab/ #to change de owner of /k8s-lab/ directory
