FROM tomcat:latest

LABEL ORGANIZATION="www.unixcloudtrainings.com"

COPY ./webapp.war /usr/local/tomcat/webapps

#Create Dockerfile under /opt/k8s-lab/"file-name"
#Which means /k8s-lab/ directory should be created before creating Dockerfile "file"
