---
- name: create service for deployment
  hosts: kubernetes
  become: true
  user: root

  tasks:
  - name: create a service
    command: kubectl apply -f uct-service.yml

#Create k8s-uct-service.yml under /opt/k8s-lab/"file-name"
#Which means /k8s-lab/ directory should be created before creating k8s-uct-service.yml "file"
#sudo chown -R ubuntu:ubuntu k8s-lab/ #to change de owner of /k8s-lab/ directory in case we have different root as owner
